# syntax=docker/dockerfile:1
FROM python:3.11-slim-bullseye

WORKDIR /app

# Сначала копируем requirements.txt
COPY requirements.txt .

# Затем используем секрет и кэш для установки пакетов
RUN --mount=type=secret,id=pip_config,target=/root/.pip/pip.conf \
    --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt

COPY . .

CMD ["python", "app.py"]
