pipeline {
    agent any
    
    stages {
        stage('Test') {
            steps {
                sh 'echo "Running tests..."'
                sh 'echo "All tests passed!"'
            }
        }
    }
}
